#scheme: http
#hostname: localhost
#
#reverse-proxy-port: 7080
reverse-proxy-uri: http://localhost:7080

authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}

bff-prefix: /bff
react-prefix: /react-ui
bff-post-logout-endpoint: /post-logout

client:
  id: client
  secret-hash: '{bcrypt}$2a$10$.ld6BfZescPDfVVduvu.6O9.7FLMI64l4PfvnBZJQEBhTLFFbeKei'  #value is 'secret', must use hash because of password encoders
  internal-identifier: nidam-bff-internal-id
  login-uri: http://localhost:7080${bff-prefix}/login/oauth2/code/token-generator   # Explanation below
#  localhost here because this is the same as bff\src\main\resources\application.yml, for docker purposes.
  logout-uri: http://localhost:7080${react-prefix}
  bff-post-logout-uri: http://localhost:7080${bff-prefix}${bff-post-logout-endpoint}     # TODO this change will break docker-compose.yml: update file


server:
  port: 4002
  servlet:
    contextPath: /auth
  forward-headers-strategy: framework

keystore:
  password: keypass
  privateKey: keystore.jks
  alias: alias

# first in the list is the default encoder
custom:
  password:
    encoders:
      - scrypt
      - bcrypt
      - argon2
      - pbkdf2
    idless: scrypt    # encoder for hashes without {id}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nidam_benchmark
    username: root
    password: CcmN*`6@3T9H%P#yg^V<7v
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    open-in-view: false

rate-limiter:
  enabled: true
  lockout-duration: 5    # minutes
  max-attempts: 5
  cleanup-interval-ms: 60000      # miliseconds

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.web: INFO
    reactor.netty: INFO
    io.netty: INFO
    io.projectreactor:
#    org.apache.tomcat.util.net.NioEndpoint: INFO
    org.apache.tomcat: INFO
    org.springframework.boot: INFO
    org.springframework.beans: INFO
    org.apache.catalina.session.ManagerBase: INFO
#trace: true
